name: Build and Deploy
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Dependencies
        run: npm install
      - name: Create .env file from GitHub Secrets
        run: |
            echo "VITE_API_KEY=${{ secrets.VITE_API_KEY }}" >> .env
            echo "VITE_AUTH_DOMAIN=${{ secrets.VITE_AUTH_DOMAIN }}" >> .env
            echo "VITE_PROJECT_ID=${{ secrets.VITE_PROJECT_ID }}" >> .env
            echo "VITE_STORAGE_BUCKET=${{ secrets.VITE_STORAGE_BUCKET }}" >> .env
            echo "VITE_MESSAGING_SENDER_ID=${{ secrets.VITE_MESSAGING_SENDER_ID }}" >> .env
            echo "VITE_APP_ID=${{ secrets.VITE_APP_ID }}" >> .env
      - name: Build
        run: npm run build

      - name: Copy build from flutter project
        run: |
          git clone https://github.com/Julian-Diaz01/randomPokemon build-temp-flutter
          cp -r build-temp-flutter/build/web/* build/

      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting --project myportfolio-16d89
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
